### PR TITLE
Error messages translation - PG-69

### PR DESCRIPTION
**Pull request by marracz**

### CODE REVIEW

**Comment by marracz** [comment]
I would like to move messages into another file and use it as a constants but it doesn't work when I try to do this analogical as in http-statuses.js

**Comment by Manfed** [comment]
1. If you want to create this in a http-statuses way, you probably should use a separate service.
2. Why did you remove all console.log() ?

**Comment by marracz** [comment]
I did remove all console.log() because I think that we shouldn't use it in our code. Eventually we can use logger instead console.log.

**Comment by nkowalik** [comment]
Everything seems to work fine except... when you try to log in and you typed wrong login or password, you receive: "{"status":404,"group":"Users","ID":"NotExists"}". I don't know whether it is easy to fix.

**Comment by Manfed** [comment]
Maybe let's use a logger, but don't allow our system to fail silently.
It's not a good approach to hide all error logs. When some error occurs, there will be no clue what's happened.

**Pull request merged**
