### PR TITLE
PG-51: Removed password from api's response

### PR DESCRIPTION
**Pull request by Manfed**

### CODE REVIEW

**Comment by Manfed** [comment]
@marta15 Please check it.

**Comment by marta15** [comment]
Works fine for both endpoints :-)

**Comment by marta15** [comment]
I found a problem with creating a new project - trying to delete password for result equal to null causes an error.

**Comment by Manfed** [comment]
@marta15 Now should be ok, please check it :)

**Comment by marta15** [comment]
Now works without errors :)

**Pull request merged**
